spring.application.name=integration

openai.api-key=${OPEN_AI_KEY:}
openai.model=gpt-4o-mini


perplexity.api.url=https://api.perplexity.ai/chat/completions
perplexity.api.key=${PERPLEXITY_API_KEY:}
perplexity.api.model=sonar-pro